root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector1\",\"posmom_poszed0\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector1\",\"posmom_poszed1\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector1\",\"posmom_poszed2\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector1\",\"posmom_poszed3\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector1\",\"posmom_poszed4\"\)

root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector1\",\"posmom_negzed0\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector1\",\"posmom_negzed1\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector1\",\"posmom_negzed2\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector1\",\"posmom_negzed3\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector1\",\"posmom_negzed4\"\)

root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector1\",\"negmom_poszed0\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector1\",\"negmom_poszed1\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector1\",\"negmom_poszed2\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector1\",\"negmom_poszed3\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector1\",\"negmom_poszed4\"\)

root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector1\",\"negmom_negzed0\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector1\",\"negmom_negzed1\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector1\",\"negmom_negzed2\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector1\",\"negmom_negzed3\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector1\",\"negmom_negzed4\"\)

root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector2\",\"posmom_poszed0\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector2\",\"posmom_poszed1\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector2\",\"posmom_poszed2\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector2\",\"posmom_poszed3\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector2\",\"posmom_poszed4\"\)

root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector2\",\"posmom_negzed0\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector2\",\"posmom_negzed1\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector2\",\"posmom_negzed2\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector2\",\"posmom_negzed3\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector2\",\"posmom_negzed4\"\)

root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector2\",\"negmom_poszed0\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector2\",\"negmom_poszed1\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector2\",\"negmom_poszed2\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector2\",\"negmom_poszed3\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector2\",\"negmom_poszed4\"\)

root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector2\",\"negmom_negzed0\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector2\",\"negmom_negzed1\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector2\",\"negmom_negzed2\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector2\",\"negmom_negzed3\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"plusplus\",\"sector2\",\"negmom_negzed4\"\)

root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector1\",\"posmom_poszed0\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector1\",\"posmom_poszed1\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector1\",\"posmom_poszed2\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector1\",\"posmom_poszed3\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector1\",\"posmom_poszed4\"\)

root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector1\",\"posmom_negzed0\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector1\",\"posmom_negzed1\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector1\",\"posmom_negzed2\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector1\",\"posmom_negzed3\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector1\",\"posmom_negzed4\"\)

root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector1\",\"negmom_poszed0\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector1\",\"negmom_poszed1\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector1\",\"negmom_poszed2\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector1\",\"negmom_poszed3\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector1\",\"negmom_poszed4\"\)

root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector1\",\"negmom_negzed0\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector1\",\"negmom_negzed1\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector1\",\"negmom_negzed2\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector1\",\"negmom_negzed3\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector1\",\"negmom_negzed4\"\)

root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector2\",\"posmom_poszed0\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector2\",\"posmom_poszed1\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector2\",\"posmom_poszed2\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector2\",\"posmom_poszed3\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector2\",\"posmom_poszed4\"\)

root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector2\",\"posmom_negzed0\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector2\",\"posmom_negzed1\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector2\",\"posmom_negzed2\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector2\",\"posmom_negzed3\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector2\",\"posmom_negzed4\"\)

root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector2\",\"negmom_poszed0\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector2\",\"negmom_poszed1\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector2\",\"negmom_poszed2\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector2\",\"negmom_poszed3\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector2\",\"negmom_poszed4\"\)

root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector2\",\"negmom_negzed0\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector2\",\"negmom_negzed1\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector2\",\"negmom_negzed2\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector2\",\"negmom_negzed3\"\)
root -b -l -q fit_sigmalized_zedmom_v3.C\(\"minusminus\",\"sector2\",\"negmom_negzed4\"\)

